export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const CLEAR_USER_LIST = 'CLEAR_USER_LIST';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USERS_BY_NAME = 'GET_USERS_BY_NAME';
export const GET_USERS_BY_NAME_FAIL = 'GET_USERS_BY_NAME_FAIL';
export const GET_USERS_BY_NAME_SUCCESS = 'GET_USERS_BY_NAME_SUCCESS';
