export const GET_TRENDING_REPOSITORIES = 'GET_TRENDING_REPOSITORIES';
export const GET_TRENDING_REPOSITORIES_FAIL = 'GET_TRENDING_REPOSITORIES_FAIL';
export const GET_TRENDING_REPOSITORIES_SUCCESS = 'GET_TRENDING_REPOSITORIES_SUCCESS';
